### ISSUE TITLE
Release Policy

### ISSUE THREAD

**Issue by mkohlhaas** [waxeye-org/waxeye#106]
The last release has been six years ago. What is the release policy of the project? Would be advantageous to have it eg. in Void Linux. But Void Linux only allows packages from official releases.

Awesome project!

**Comment by glebm** [comment]
I can tag a release here but I don't have access to publish waxeye runtime packages, such as https://www.npmjs.com/package/waxeye, https://rubygems.org/gems/waxeye, https://pypi.org/project/waxeye, etc. @orlandohill, can you publish these or give me access? Thanks

**Comment by mkohlhaas** [comment]
Hi Gleb,

thanks for your support. Racket should also be deployed to the [Racket packages repository](https://pkgs.racket-lang.org/): see also [no racket pkg #87](https://github.com/waxeye-org/waxeye/issues/87). With `raco` it should be relatively easy to do. For docs see [Official raco documentation](https://docs.racket-lang.org/raco/) and [Raco package tutorial](https://blog.racket-lang.org/2017/10/tutorial-creating-a-package.html).

**Comment by orlandohill** [comment]
Hi Michael, thanks for suggesting this. I'll start releasing new versions later this month. I'll deploy Waxeye to the Racket Package Index, and do likewise for the other languages that have package repos.

**Comment by orlandohill** [comment]
Hi Thomas,

Thanks for reporting this bug!

There were some big delays on my end, but I'm back to development now.

As a rough schedule, I'm aiming to release a new version this month that just supports Racket, and then add support for an additional language every 1-2 weeks.

The order would be something like the following:

* Racket
* Java
* TypeScript/JavaScript
* Python
* Ruby
* C#
* PHP
* Go
* Swift
* Rust

I'm not sure how much priority to give C/C++ and HaXe in the short term.

**Comment by bkil** [comment]
Sounds nice. I'm using Java/Scala at the moment, and Python may come in handy for my peers.

I also wanted to test performance via C/C++ out of curiosity, but unfortunately Unicode literals spoiled the generated code.

**Comment by orlandohill** [comment]
Thanks, that's helpful to know!
