### ISSUE TITLE
Skip parser generation if parser is up-to-date

### ISSUE THREAD

**Issue by bzaar** [waxeye-org/waxeye#16]
When running the `waxeye -g` command for a C target it would make sense not to update the `parser.c` and `parser.h` files if their dates are older than the that of the grammar file.  That's the default behaviour for a C compiler (if the .obj is older, skip the .c file).  This saves a lot of build time.  Would be nice if waxeye had this capability.  

Otherwise, this is the best parser I've come across (and I've tried a few).  Thanks a lot for your work.

**Comment by orlandohill** [comment]
Hi, thanks for suggesting this feature.

I think it makes more sense to rely on a build system (Make, Scons, Ninja, etc) for this functionality.

I'll close this issue for now.
