### ISSUE TITLE
Moving to waxeye/ org

### ISSUE THREAD

**Issue by glebm** [waxeye-org/waxeye#94]
Hi @orlandohill!

Do you mind setting up a waxeye org, moving the repo there, and giving ownership to me and @jishi9, so that we can continue development?

**Comment by orlandohill** [comment]
Yes, that sounds good.

Do we need the 'waxeye' GitHub username? I could contact GitHub to get
access. Not sure if I registered it or not, but either way I don't think
it's being used.

>

**Comment by glebm** [comment]
There does seem to be an account with that name: https://github.com/waxeye
Registered 2016, doesn't seem to be used.

Looks like GitHub has a process for claiming unused names: https://help.github.com/en/github/site-policy/github-username-policy

If GitHub doesn't give it to us, perhaps we can name the org `waxeye-org` instead.

**Comment by orlandohill** [comment]
It looks like I could only request the `waxeye` username if there was a trademark violation.

**Comment by glebm** [comment]
Perfect, thank you!
